version: "3.9"

services:
  # Service PostgreSQL
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service FastAPI
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DATABASE}
      DB_USER: ${USER}
      DB_PASSWORD: ${PASSWORD}
      HF_TOKEN: ${HF_TOKEN}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
