version: "3.9"

services:
  # Service PostgreSQL
  db:
    image: postgres:15
    restart : always 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: DATABASE
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service FastAPI
  app:
    build: .
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: DATABASE
      DB_USER: USER
      DB_PASSWORD: 123
      # HF_TOKEN: HF_TOKEN
      # SECRET_KEY: SECRET_KEY
      # ALGORITHM: ALGORITHM

    
    volumes:
      - .:/app
    command: sh -c "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

    

volumes:
  postgres_data:


